language: java
install: 
- mvn -pl "!doc" install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
# add login credentials in registry
- java -cp environment/target/tygronenv-*-jar-with-dependencies.jar login.Login $email $password
# test the code
- mvn test
jdk:
- oraclejdk8

