install: mvn -pl "!doc" install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: 
- java -cp environment/target/tygronenv-*-jar-with-dependencies.jar login.Login $email $password
- maven pmd
- mvn test
jdk:
- oraclejdk8
